const ErrorMessages = {
  USER_NOT_FOUND: "User Not Found",
  GUEST_NOT_FOUND: "Guest Not Found",
  INVALID_INPUT: "Invalid Input Provided",
  UNAUTHORIZED: "Unauthorized Access",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  INVALID_VERIFICATION_CODE: "Invalid Verification Code",
  VERIFICATION_CODE_EXPIRE: "Verification Code Is Expired",
  USER_ALREADY_EXIST: "User Already Exist",
  UNEXPECTED_ERROR: "Unexpected Error",
  SEND_VERIFICATION_CODE_FAILURE: "Fail to send verification code",
  INVALID_EMAIL_AND_PASSWORD: "Invalid Email or Password",
  INVALID_TOKEN: "Invalid Token",
  COOKIE_NOT_FOUND: "Cookie Not Found",
  TOKEN_NOT_FOUND: "Token Not Found",
  INVALID_FILE_FORMAT: "Invalid File Format",
  FRIEND_REQUEST_ALREADY_SENT: "Friend request is already been sent",
  ORIGINAL_PASSWORD_NOT_MATCH: "Not match with original password",
  PASSWORD_IS_CURRENTLY_USED: "This password is currently used",
  SEND_CHANGE_EMAIL_LINK_FAILURE: "Fail to send change email link",
  CHANGE_EMAIL_LINK_EXPIRES: "Change email link expires",
  PHOTO_NOT_FOUND: "Photo Not Found",
  MULTIMEDIA_NOT_FOUND: "Multimedia Not Found",
  VIDEO_NOT_FOUND: "Video Not Found",
  TOILET_NOT_FOUND: "Toilet Not Found",
  TOILET_LOCATION_NOT_FOUND: "Toilet Location Not Found",
  ALREADY_FRIEND: "You are friends with this user already",
  REWARD_NOT_FOUND: "Reward Not Found.",
  INSUFFICIENT_COINS: "Insufficient Coins",
  REWARD_REDEEMED: "Reward has been redeemed before",
};

const SuccessMessages = {
  VERIFICATION_SUCCESS: "Verification Success",
  SEND_VERIFICATION_CODE_SUCCESS: "Verification code is sent",
  REGISTER_SUCCESS: "User Registration Success",
  LOGIN_SUCCESS: "Login Success",
  LOGOUT_SUCCESS: "Logout Success",
  SEND_VERIFICATION_CODE_SUCCESS: "Verification code is sent",
  SEND_RESET_PASSWORD_LINK_SUCCESS: "Reset password link is sent",
  RESET_PASSWORD_SUCCESS: "Reset Password Success",
  GET_TOKEN_VALUE_SUCCESS: "Get Token Value Success",
  GET_USER_DATA_SUCCESS: "Get User Data Success",
  GET_GUEST_DATA_SUCCESS: "Get Guest Data Success",
  GET_USER_FRIENDS_DATA_SUCCESS: "Get User Friends Data Success",
  GET_GUEST_FRIENDS_DATA_SUCCESS: "Get Guest Friends Data Success",
  GET_CREDENTIAL_SUCCESS: "Get Credential Success",
  CLEAR_COOKIES_SUCCESS: "Clear Cookies Success",
  EDIT_PERSONAL_DETAILS_SUCCESS: "Edit Personal Details Success",
  EDIT_USER_AVATAR_SUCCESS: "Edit User Avatar Success",
  EDIT_USER_BANNER_SUCCESS: "Edit User Banner Success",
  GET_USERS_IN_BATCH_SUCCESS: "Get User In Batch Success",
  SEND_FRIEND_REQUEST_SUCCESS: "Send Friend Request Success",
  GET_USER_FRIEND_REQUESTS_SUCCESS: "Get Friend Requests Success",
  GET_GUEST_FRIEND_REQUESTS_SUCCESS: "Get Guest Friend Requests Success",
  FRIEND_REQUEST_ACCEPTED: "Friend Request Accepted",
  FRIEND_REQUEST_REFUSED: "Friend Request Refused",
  UNFOLLOW_FRIEND_SUCCESS: "Unfollow Friend Success",
  GET_USER_NOTIFICATIONS_SUCCESS: "Get User Notification Success",
  CANCEL_NOTIFICATION_SUCCESS: "Cancel Notification Success",
  CHANGE_USER_PREFERENCE_LANGUAGE_SUCCESS:
    "Change User Preference Language Success",
  CHANGE_USER_PREFERENCE_COLORBLIND_SUCCESS:
      "Change User Preference Colorblind Success",
  GET_USER_TOILET_PHOTOS_SUCCESS: "Get User Toilet Photos Success",
  GET_GUEST_TOILET_PHOTOS_SUCCESS: "Get Guest Toilet Photos Success",
  CHANGE_PASSWORD_SUCCESS: "Change Password Success",
  SEND_CHANGE_EMAIL_LINK_SUCCESS: "Send Change Email Link Success",
  CHANGE_EMAIL_SUCCESS: "Change Email Success",
  DELETE_USER_TOILET_PHOTO_SUCCESS: "Delete User Toilet Photo Success",
  DELETE_USER_TOILET_VIDEO_SUCCESS: "Delete User Toilet Video Success",
  LIKE_SUCCESS: "Like Success",
  DISLIKE_SUCCESS: "Dislike Success",
  ADD_COMMENT_SUCCESS: "Add Comment Success",
  ADD_VIDEO_COMMENT_SUCCESS: "Add Video Comment Success",
  GET_USER_TOILET_VIDEOS_SUCCESS: "Get User Toilet Videos Success",
  GET_GUEST_TOILET_VIDEOS_SUCCESS: "Get Guest Toilet Videos Success",
  GET_TOILET_NEARBY_SUCCESS: "Get Toilet Nearby Success",
  UPDATE_TOILET_RATING_SUCCESS: "Update Toilet Rating Success",
  ADD_TOILET_COMMENT_SUCCESS: "Add Toilet Comment Success",
  UPDATE_TOILET_BOOKMARK_SUCCESS: "Update Toilet To Bookmark Success",
  GET_ALL_VERIFIED_TOILET_DATA_SUCCESS: "Get all verified Toilet Data Success",
  GET_ALL_NON_VERIFIED_TOILET_DATA_SUCCESS:
    "Get all non-verified Toilet Data Success",
  GET_ALL_NON_VERIFIED_MULTIMEDIA_SUCCESS:
    "Get all non-verified multimedia Success",
  ADD_TOILET_SUCCESS: "Add Toilet Success",
  DELETE_NON_VERIFIED_TOILET_SUCCESS: "Delete Non-verified Toilet Success",
  APPROVE_NON_VERIFIED_TOILET_SUCCESS: "Approve Non-verified Toilet Success",
  GET_REWARDS_DATA_SUCCESS: "Get Rewards Data Success",
  EXCHANGE_REWARD_SUCCESS: "Exchange Reward Success",
  APPROVE_NON_VERIFIED_MULTIMEDIA_SUCCESS:
    "Approve Non-verified Multimedia Success",
  DELETE_NON_VERIFIED_MULTIMEDIA_SUCCESS:
    "Delete Non-verified Multimedia Success",
    CHANGE_PREFERENCE_MARKER_SUCCESS: "Change Preference Marker Success",
};

export { ErrorMessages, SuccessMessages };
