const userDataFormatter = (user) => {
  return {
    userId: user?._id,
    role: user?.role,
    email: user?.email,
    fullname: user?.fullname,
    username: user?.username,
    userAvatar: user?.userAvatar,
    userBanner: user?.userBanner,
    followers: user?.followers,
    friends: user?.friends,
    tel_country_code: user?.tel_country_code,
    phone: user?.phone,
    location: user?.location,
    preference_language: user?.preference_language,
    preference_font_size: user?.preference_font_size,
    preference_theme: user?.preference_theme,
    preference_colorblind: user?.preference_colorblind,
    preference_marker: user?.preference_marker,
    toilet_bookmarks: user?.toilet_bookmarks?.map((bookmark) => ({
      toiletId: bookmark._id,
      name_en: bookmark.name_en,
      name_zh: bookmark.name_zh,
      address_en: bookmark.address_en,
      address_zh: bookmark.address_zh,
      district_en: bookmark.district_en,
      district_zh: bookmark.district_zh,
      location: bookmark.location,
      rating: bookmark.rating,
      views: bookmark.views,
      comments: bookmark.comments,
      isMale: bookmark.isMale,
      isFemale: bookmark.isFemale,
      isDisabled: bookmark.isDisabled,
      haveBathroom: bookmark.haveBathroom,
    })),
    coins: user?.coins,
    exchange_records: user?.exchange_records?.map((record) => ({
      recordId: record._id,
      reward: record.reward,
      exchanged_at: record.exchanged_at,
    })),
    tasks: user?.tasks?.map((task) => ({
      taskId: task._id,
      title: task.title,
      category: task.category,
      description: task.description,
      coins: task.coins,
      last_completed_at: task.last_completed_at,
      cooldown: task.cooldown,
      isCompleted: task.isCompleted,
    })),
    login_history: user?.login_history,
  };
};

export default userDataFormatter;
