const QUERY_KEYS = {
  USER_DATA: "USER_DATA",
  GUEST_DATA: "GUEST_DATA",
  USER_FRIENDS_DATA: "USER_FRIENDS_DATA",
  GUEST_FRIENDS_DATA: "GUEST_FRIENDS_DATA",
  USER_FRIEND_REQUESTS_DATA: "FRIEND_REQUESTS_DATA",
  GUEST_FRIEND_REQUESTS_DATA: "GUEST_REQUESTS_DATA",
  USER_RESET_PASSWORD_CREDENTIAL: "USER_RESET_PASSWORD_CREDENTIAL",
  USER_REGISTRATION_CREDENTIAL: "USER_REGISTRATION_CREDENTIAL",
  USER_CHANGE_EMAIL_CREDENTIAL: "USER_CHANGE_EMAIL_CREDENTIAL",
  USER_NOTIFICATIONS: "USER_NOTIFICATIONS",
  VERIFIED_TOILET_DATA: "VERIFIED_TOILET_DATA",
  NON_VERIFIED_TOILET_DATA: "NON_VERIFIED_TOILET_DATA",
  NON_VERIFIED_MULTIMEDIA: "NON_VERIFIED_MULTIMEDIA",
  REWARDS_DATA: "REWARDS_DATA",
};

export default QUERY_KEYS;
